### ISSUE TITLE
local.json missing

### ISSUE THREAD

**Issue by LNdame** [MDSADABWASIM/Toughest#1]
Hi there
any chance you could share the asset/local.json ? it is missing from the git

**Comment by MDSADABWASIM** [comment]
Sure here you go @LNdame and @bhanu888 , local.json is in this format-----

`{
    "Behaviour": [
      {
        "Q": "Tell me about how you worked effectively under pressure?",
        "A": "answer "
      },
      {
        "Q": "How aware are you of internal politics that may affect your performance?",
        "A": "answer."
      },
 ],
    "Communication": [
      {
        "Q": "question",
        "A": "answer"
      },
],
......
}`

**Comment by MDSADABWASIM** [comment]
I hope that will be enough to close this issue.

**Comment by MDSADABWASIM** [comment]
I've added **local.json** file in asset folder, so that everyone can use it.
