### ISSUE TITLE
dependencies conflict while running

### ISSUE THREAD

**Issue by gopalkumr** [MDSADABWASIM/Toughest#12]
while running the app 'Toughest'. I'm getting dependencies conflict error
![image](https://github.com/MDSADABWASIM/Toughest/assets/91552766/1c118a95-f5a1-49e8-ae12-a36d1929ac76)

`$ flutter run
Resolving dependencies... (4.8s)
Note: file is pinned to version 7.0.0 by flutter_driver from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because share_plus ^4.0.1 depends on share_plus_linux ^3.0.0 which depends on file ^6.0.0, share_plus
  ^4.0.1 requires file ^6.0.0.
And because every version of flutter_driver from sdk depends on file 7.0.0, share_plus ^4.0.1 is
  incompatible with flutter_driver from sdk.
So, because toughest depends on both share_plus ^4.0.10+1 and flutter_driver from sdk, version solving
  failed.

You can try the following suggestion to make the pubspec resolve:
* Try upgrading your constraint on share_plus: flutter pub add share_plus:^9.0.0`

**Comment by gopalkumr** [comment]
after upgrading the share_plus to version 4.0.1. we are getting an error prompted to set 'compileSdkVersion' to be set to 33 or higher. currently, it is at 32.
![image](https://github.com/MDSADABWASIM/Toughest/assets/91552766/a6a1e6dd-dce8-4da4-a439-1ae58f33b74f)

**Comment by gopalkumr** [comment]
please assign this task to me so I can fix and create a new pull request

**Comment by MDSADABWASIM** [comment]
Hi @gopalkumr you can directly create a PR for it. If that fixes the issue then I'll merge it.

**Comment by MDSADABWASIM** [comment]
@gopalkumr you can try rerunning it, I've made it compatible with the latest Flutter version.

If you find the issue again, feel free to comment that here.
