### ISSUE TITLE
( BUG Toughest VERSION 2.0.2 ) When I try to open the application, then the application crashes

### ISSUE THREAD

**Issue by friendsmobile** [MDSADABWASIM/Toughest#2]
# Project Information

* Repository:  https://github.com/MDSADABWASIM/Toughest
* Project Name:  	Tricky questions and answer
* My Github Account: https://github.com/friendsmobile
* Download the application:  https://play.google.com/store/apps/details?id=tricky.questions

# Expected behavior

When I try to open the application, the application should be open so that users can easily use all the options in the application.

# Actual behavior

When I try to open the application, then the application crashes

#### How to reproduce

* [Download ](https://play.google.com/store/apps/details?id=tricky.questions)the application
*  try to open the applicationon 
* Note the Error

* Browser/App version:  2.0.2
* Operating system: 6.0

#### Recording Of The Bug

![20190713_153824](https://user-images.githubusercontent.com/51118734/61170578-0f8dd280-a520-11e9-8386-42dacc78e671.gif)

#### Logcat

<pre><code>D/AndroidRuntime(21764): Shutting down VM

E/AndroidRuntime(21764): FATAL EXCEPTION: main

E/AndroidRuntime(21764): Process: tricky.questions, PID: 21764

E/AndroidRuntime(21764): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tricky.questions-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libflutter.so"

E/AndroidRuntime(21764): 	at java.lang.Runtime.loadLibrary(Runtime.java:366)

E/AndroidRuntime(21764): 	at java.lang.System.loadLibrary(System.java:988)

E/AndroidRuntime(21764): 	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:122)

E/AndroidRuntime(21764): 	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:99)

E/AndroidRuntime(21764): 	at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)

E/AndroidRuntime(21764): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1019)

E/AndroidRuntime(21764): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4991)

E/AndroidRuntime(21764): 	at android.app.ActivityThread.access$1600(ActivityThread.java:177)

E/AndroidRuntime(21764): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1491)

E/AndroidRuntime(21764): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime(21764): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(21764): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(21764): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(21764): 	at java.lang.reflect.Method.invoke(Method.java:372)
</code></pre>

**Comment by MDSADABWASIM** [comment]
Make sure your project is migrated to AndroidX, if not then [https://medium.com/@swhussain110/how-to-migrate-your-flutter-app-to-androidx-9a78eaaa924b](follow this).

**Comment by friendsmobile** [comment]
hello @MDSADABWASIM  your link article not founding I think a link is wrong 

![image](https://user-images.githubusercontent.com/51118734/62005247-544f6700-b0e5-11e9-97e4-9bab848dab9d.png)

**Comment by MDSADABWASIM** [comment]
Sorry for the late response here's another link [https://flutter.dev/docs/development/androidx-migration](url)

**Comment by MDSADABWASIM** [comment]
I think this will be enough to close this issue, reopen it if you get the same problem.
