### ISSUE TITLE
Font and Color

### ISSUE THREAD

**Issue by nitishpatel** [MDSADABWASIM/Toughest#4]
The Color of the text in the app drawer is not visible at all

**Comment by rish07** [comment]
Hi @nitishpatel, could you please post a screenshot?

**Comment by aggarwalnaman** [comment]
![WhatsApp Image 2020-05-04 at 12 59 40 AM](https://user-images.githubusercontent.com/42396114/80923661-9dce9000-8da2-11ea-84de-c7ab2425611d.jpeg)


See this!!..

May I change this color and font in this app drawer

**Comment by nitishpatel** [comment]
Yeah i was telling about this font and color, sry for not posting the screenshot

**Comment by MDSADABWASIM** [comment]
HI @nitishpatel, just change the color you think will fit here and send a pull request.

**Comment by MDSADABWASIM** [comment]
Thanks @nitishpatel  for the PR, I've merged it.
